/*
 * Copyright (C) 2015 PÂRIS Quentin
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package com.playonlinux.win32.registry;

public class RegistryWriter {
    private String buildRegTreeString(AbstractRegistryNode node) {
        final StringBuilder generatedRegFileBuilder = new StringBuilder();
        generatedRegFileBuilder.append(node.toRegString()).append("\n");

        if(node instanceof RegistryKey) {
            for (AbstractRegistryNode child : ((RegistryKey) node).getChildren()) {
                generatedRegFileBuilder.append(buildRegTreeString(child));
            }
        }
        return generatedRegFileBuilder.toString();
    }

    public String generateRegFileContent(AbstractRegistryNode node) {
        return String.join("\n", "WINE REGISTRY Version 2",
                ";; Generated by PlayOnLinux", buildRegTreeString(node));
    }
}
