#!/usr/bin/bash

POL_Config_PrefixRead ()
{
	# Read an entry in wine current prefix's config file
	# Usage : POL_Config_PrefixRead [KEY]

	cat "$WINEPREFIX/playonlinux.cfg" 2> /dev/null | grep "^$1=" | cut -d\= -f2-
}