#!/usr/bin/bash

POL_System_SetArch()
{
	# Set the architecture to use for the current script
	# Usage: POL_System_SetArch (auto|x86|amd64)
	# If amd64 is specified and not supported, the script will end

	# $1 = Auto, x86, amd64
	# $2 = detected, if the result of an automatic selection

	if [ ! "$1" == "x86" ] && [ ! "$1" == "amd64" ]
	then
		[ "$AMD64_COMPATIBLE" == "True" ] && export POL_ARCH="amd64" || export POL_ARCH="x86"
	fi
	if [ "$1" == "x86" ]
	then
		export POL_ARCH="x86"
	fi
	if [ "$1" == "amd64" ]
	then
		[ "$AMD64_COMPATIBLE" == "True" ] && export POL_ARCH="amd64" || POL_Debug_Fatal "amd64 is not supported by your system"
	fi

	[ "$2" = "detected" ] || POL_USER_ARCH="$POL_ARCH"

	POL_Debug_Message "POL_ARCH set to $POL_ARCH"
}