source "https://rubygems.org"

gem "jekyll"
gem "jekyll-remote-theme"

gem "github-pages", group: :jekyll_plugins

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "html-proofer"
