package com.playonlinux.containers.wine.parameters;

import com.playonlinux.win32.registry.RegistryWriter;

import static org.junit.Assert.assertEquals;

public abstract class AbstractRegistryParameterTest<T extends RegistryParameter> {
    private final RegistryWriter registryWriter = new RegistryWriter();

    protected void testStringValue(T value, String expected) {
        assertEquals("WINE REGISTRY Version 2\n" +
                ";; Generated by PlayOnLinux\n" +
                "\n" +
                "[HKEY_CURRENT_USER\\Software\\Wine\\Direct3D]\n" +
                "\""+value.getClass().getSimpleName()+"\"=\""+expected+"\"", registryWriter.generateRegFileContent(value.toRegistryPatch()).trim());
    }

    protected void testRemoveValue(T value) {
        assertEquals("WINE REGISTRY Version 2\n" +
                ";; Generated by PlayOnLinux\n" +
                "\n" +
                "[HKEY_CURRENT_USER\\Software\\Wine\\Direct3D]\n" +
                "\""+value.getClass().getSimpleName()+"\"=-", registryWriter.generateRegFileContent(value.toRegistryPatch()).trim());
    }
}
